# Site settings
title: palais - AI development toolkit
email: admin@palais.io
description: > # this means to ignore newlines until "baseurl:"
  Palais is a free simulation environment for Artificial Intelligence in Games.
  It provides much of the common functionality required for authoring, testing 
  and prototyping of AI behaviors.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://palais.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  palais-ai

# Build settings
markdown: kramdown
